
name: Build Translator App

on: [push]

jobs:
  build:
    
    runs-on: windows-latest

    steps:
      - name: Checkout repository to the Virtual Machine
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --distpath ./build --windowed --icon=resources\icon.ico --add-data "resources;resources" translator.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Executable
          path: build/translator.exe